- package.json
- src/pages/article-page.ts
- src/pages/reviews.ts
- src/reviews/fetch-reviews.ts
- src/server.ts
- yarn.lock
> Add reviews page

- src/pages/article-page.test.ts
add empty string to the doi parameter as it is not needed for the tests
> fix broken test

- .dockerignore
- Dockerfile
- Dockerfile.Watch
- Makefile
- package.json
- scripts/watch.sh
Added a dockerfile for running the watch targets in and a makefile for building and running the image.
Closes #40
> add dockerfile and makefile for watching sass and ts changes

- src/article-list/article-list.ts
- src/article/article.test.ts
- src/article/article.ts
- src/base-page/base-page.ts
- src/reviews/reviews.ts
- src/server.ts
> Base page template

- src/article/index.scss
- src/sass/_settings.scss
- Add a border-bottom to the content header as a divider
- Move padding of main content into correct break point
- Correct vertical align on ToC and Abstract header
- Add simple hover border colour change, so that `--selected` ToC colour can be previewed (before we have updating on scroll)
> Misc improvements

- src/article/article.ts
- src/article/index.scss
> add hardcoded article status

- src/article/article.ts
- src/article/index.scss
- src/base-page/base-page.ts
- src/base-page/index.scss
- src/sass/_settings.scss
- src/sass/style.scss
Reorg the grid to be part of the basePage too
> Move the logo into a banner container in the grid

- src/article/article.ts
- src/article/index.scss
- src/sass/_buttons.scss
- src/sass/_typography.scss
> add article metadata to right bar

- README.md
> update readme with useful commands

- src/article/index.scss
> fix layout for narrow view of right column

- src/article/article.ts
- src/article/styles/right-column.scss
> fix position of right column

- src/article/article.ts
- src/article/styles/article.scss
- src/article/styles/right-column.scss
- src/sass/_grid.scss
> fix position of jump-to-menu

- src/reviews/index.scss
- src/reviews/reviews.ts
Improves on: https://github.com/elifesciences/enhanced-preprints/issues/117
> Style the back to article button

- src/article/article-evaluation-summary.ts
- src/article/article-page.ts
- src/article/index.scss
- src/article/jump-to-menu.ts
- src/article/styles/evaluation-summary.scss
> Hardcode editors evaluation summary on article page

- src/article/index.scss
- src/article/styles/article.scss
- src/article/styles/header.scss
- src/reviews/index.scss
- src/reviews/reviews.ts
- src/sass/_layout.scss
- src/sass/style.scss
> Review page layout

- src/reviews/index.scss
- src/reviews/reviews.ts
- src/sass/_buttons.scss
- src/sass/_settings.scss
- src/sass/_typography.scss
> Add static review-summary with badges

- src/article/article-page.ts
- src/article/styles/article.scss
- src/reviews/index.scss
- src/reviews/reviews.ts
> Decouple the styling for article body from the layout main-content-area

- src/model/model.ts
- src/reviews/fetch-reviews.test.ts
- src/reviews/fetch-reviews.ts
- src/reviews/get-enhanced-article.ts
- src/reviews/reviews.ts
- test-utils/docmap-mock.ts
Parse the new docmap structure.
> Docmap sciety reviews

- docker-compose.yaml
to stop it complaining regularly that the _users does not exist.
> fix(docker-compose): make sure to create a _users DB in couchDB 

- src/data-loader/data-loader.ts
> check database for entry before converting or storing xml

- src/reviews/index.scss
- src/reviews/reviews.ts
- src/sass/_typography.scss
> Tidy up review text on review page up to match the styles in latest designs

- src/article/article-page.ts
- src/article/jump-menu.ts
- src/model/model.ts
- src/reviews/index.scss
- src/reviews/reviews.ts
> Jump list for review page

- src/reviews/reviews-peer-review-of.ts
> fix: review-of box does not convert title content to html

- src/article/article-page.ts
> fix: correct ordering for Headings on page

- src/article/styles/article.scss
> add style for links in article body

- src/reviews/index.scss
- src/reviews/reviews.ts
> fix spacing on reviews page

- package.json
- src/config.ts
- src/model/content.ts
- src/server.ts
- src/utils/logger.ts
- yarn.lock
> Add winston logger

- src/base-page/base-page.ts
> add code for gtm

- src/article/article-flags.ts
- src/article/header.ts
- src/article/styles/header.scss
> add article msas and flags

- src/data-loader/data-loader.ts
- src/model/article-stores.test.ts
- src/model/sqlite/sqlite-repository.ts
Sorry, As I was updating tests I also removed some references to xml data that should have been removed previously, but was still included.
> fix article.content so that we import the articleStruct.content field, not a blank article html string

- package.json
- public/script.js
- src/data-loader/conversion/encode.test.ts
- src/data-loader/data-loader.ts
- yarn.lock
This PR builds on the one to downgrade stencila and add tests (#261). 
Here we reupgrade @stencila/schema, and update the code and new tests to match the new schema.
**NOTE: Review and merge #261 first, then rebase this and review.**
> Stencila schema update

- public/script.js
- src/reviews/review-summary.ts
- src/reviews/reviews-editors-and-reviewers.ts
- src/reviews/reviews.ts
> Target jump-menu elements more directly with a data-jump-menu-target attribute

- src/data-loader/data-loader.ts
> fix an issue with file paths in a symlinked directory differing from those encoda puts in the html

- docker-compose.yaml
- src/model/create-article-repository.ts
- src/model/mongodb/mongodb-repository.ts
To allow deployment on kubernetes
Fixes #285 285
> feat: allow mongodb user and password to be configured separately to the host config

- src/data-loader/data-loader.ts
Compare to the processed article DOI instead of the file path.
> fix: loading articles fails on the cluster with a duplicate ID error.

- README.md
Describe the import process better and with the new configurations. 
fixes #137
> Improve documentation around importing

- docker-compose.yaml
- src/article/header.test.ts
- src/article/header.ts
- src/data-loader/data-loader.ts
- src/model/article-stores.test.ts
- src/model/model.ts
- src/model/mongodb/mongodb-repository.ts
Wasn't sure if I should make a new type for Person without affiliations and use that for references, or use the existing type but make affiliations optional. I've gone with this for now, because I struggled with naming (`ReferenceAuthor`?) but feedback and changes to new type very welcome.
fixes https://github.com/elifesciences/enhanced-preprints-server/issues/326
> Import references

- src/data-loader/data-loader.ts
- src/model/model.ts
Some references on some papers are missing published dates. I guess we need to make that optional then.
> Fix import date failure for references

- src/reviews/fetch-reviews.ts
fixes https://github.com/elifesciences/enhanced-preprints-server/issues/413
`GET /reviewed-preprints/{doi}/reviews` From 1.2s first hit to 300ms (still fetching from sciety) on my laptop. Will rerun load tests (https://github.com/elifesciences/enhanced-preprints-client/issues/107) when merged.
> Add a simple, in-memory cache of the hypothesis responses

- src/utils/logger.ts
Related to https://github.com/elifesciences/enhanced-preprints-server/issues/419
> Allow loglevel to be set by env var

- src/reviews/fetch-reviews.ts
> switch to prod

- src/reviews/fetch-reviews.test.ts
- src/reviews/fetch-reviews.ts
fixes https://github.com/elifesciences/enhanced-preprints-server/issues/426
> Map participants roles to friendlier names, and strip the peer-reviewers

- .github/workflows/ci.yaml
- .github/workflows/preview-build.yaml
relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/324
> update gha outputs to use the newer redirect-based output

- .eslintrc.js
- package.json
- yarn.lock
Resolves https://github.com/elifesciences/enhanced-preprints-issues/issues/579
> Added no-only-tests eslint plugin

- src/controller/reviewed-preprints-controller.ts
- src/services/reviews/fetch-reviews.test.ts
- src/services/reviews/fetch-reviews.ts
- test-utils/docmap-mock.ts
Reverts elifesciences/enhanced-preprints-server#675
> Revert "Revised preprints reviews api update"

- package.json
- yarn.lock
This reverts commit fd82c76278624c46ae8fc31065f2d623551226e0.
> Revert "Update dependency @stencila/encoda to v0.121.2"

- src/config.ts
- src/server.ts
fixes https://github.com/elifesciences/enhanced-preprints-issues/issues/204
> fix: name the app in the log and make the port configurable (default to 3000)

- src/services/reviews/fetch-reviews.ts
relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/668
> fix the config for docMapsApi not being used

- yarn.lock
> Update all deps

- src/http-schema/http-schema.test.ts
- src/http-schema/http-schema.ts
- src/model/model.ts
It will keep the number if it is safe other wise if it is an unsafe number then it will be converted to a string.
Should be merged in after: https://github.com/elifesciences/enhanced-preprints-client/pull/1238
> feat: allow volumeNumber to be safe number or string

- src/model/mongodb/mongodb-repository.ts
Performance improvements:
- Include a new index for published (this should improve some other queries too, but not as much as this full collection scan).
- Move projection earlier in the pipeline so that the server has less data to move through later pipelines
> Performance improvements for nocontent api
