- src/article/article.test.ts
- src/article/article.ts
- src/article/index.scss
Experiment using JSDom, pull out the "header" items, and then generate a new article element without them there.
This may allow quickly experimenting with moving these head things elsewhere on the page.
> [RFC] experiment - can we pull out the header detail from the generated article?

- src/article/article.ts
- src/article/index.scss
- src/sass/_settings.scss
Done some basic implementation of the styles, including `--selected` even though it's not used yet.
Interested to know if there is a better way to do the menu border overlap
> Style navigation menu

- src/base-page/base-page.ts
We're not currently pulling in a weight 600 font for Noto Sans, despite using it in the typography.
Unfortunately, when asking for weight 6000 from the coollabs css2 api, it gives a font file that is status 400:
https://cdn.fonts.coollabs.io/noto-sans/normal/600.woff2
Switched back to google fonts
> Change to Google font CDN - cool labs isn't working correctly

- src/sass/_settings.scss
Due to the shifting focus of the prototype being used to validate value of preprint enhancement features, eLife branding is preferred in the short-term until we're building features "for real".
This is just changing the emphasis colour and the logo for now to eLife, while keeping the biophysics-colab ones around until we have a runtime/deploy time switching mechanism
closes #65
> Switch settings around to default to eLife Branding

- src/article-list/article-list.ts
Example:
Fix by joining with an empty string in the template.
> stop the array being rendered to comma-separated string 

- src/reviews/fetch-reviews.test.ts
- src/reviews/fetch-reviews.ts
- src/reviews/reviews.ts
- src/server.ts
- test-utils/docmap-mock.ts
@will-byrne I'm interested to know how to improve on this? 
My thinking is this: 
- Returning an empty array on failure means the logic finding a matching docmap for the `reviewingGroup` will fail, rejecting the `fetchReviews` Promise. 
- Further, if `fetchReviews()` is a rejected promise, we should display ***something***, I've chosen to return a blank array, and alter generateReviewPage to say the reviews we not found.
- 
This allows us to close #58, but feels a bit icky:
- any HTTP failure will now return a failed Promise saying "No docmap for ...", which isn't true in the case of temporary server failure or timeout. 
- Actually, all rejected promises of `fetchReviews` are treated as if there are no reviews.
I'm not familiar enough with async error handling to know a better way of …
> Fix crash on non-existent docmap

- src/config.ts
- src/data-loader/data-loader.ts
- src/server.ts
Change config to be set-able via ENV vars.
Also make import not automatic no we have a semi-permanent backing store, but allow remotely triggering import.
This will allow us to remove the articles from the repo, by attaching them in the kubernetes deployment
> Environment settings and HTTP import

- src/server.ts
This is not a side-effect free read-only action, so a GET request is very, very inappropriate.
> Use correct POST HTTP method for /import route instead of GET

- src/server.ts
Clients (such as that exhibit retry behaviour) will end up in a loop if they have no new files to import, but think they need to retry a webhook. Always return 200, just give details on what happened.
Also, add a GET on /import that allows a dev to trigger import manually easier than relying on curl or similar.
> Don't sent status 500 when calling import and all files are already imported.

- .docker/litestream.cfg
- Makefile
- README.md
- docker-compose.yaml
- src/model/couchdb/couchdb-repository.ts
Added documentation, ~but not added Makefile targets (yet).~ Will added make targets
This should bring up either a CouchDB, or SQLite ~+ minio (s3) replicated app locally,~ fully configured and setup.
The data will persist between `docker-compose up` runs (via docker anonymous volumes) and instructions for deleting volumes is included.
> Add docker-compose config, with profiles for sqlite and couchdb

- .dockerignore
- Dockerfile
We're currently building the docker image with the default yarn (v1) which does not obey the yarn.lock file.
Another consequence of this was a broken docker image that does not work on the older version of alpine we were using. 
Both these issues are fixed with these changes.
- add .yarnrc and .yarn/releases/** to build image (alter .dockerignore to allow this)
- add packages required for a successful build of deps with yarn
> fix(docker): Use yarn committed to repo when building docker image

- .docker/couchdb/doc_size.ini
- docker-compose.yaml
Also, tidy up the names of volumes a little bit, and make sure we mount data and migrations inside the containers
fixes #190
> Increase the document size for the included CouchDB container.

- renovate.json
fixes #236 .
This should reduce the number of manual interventions to major updates, with minor and patch and docker digest updates automerged once tests pass.
> Add some packagerules to automerge low-risk dependency updates

- migrations/sqlite/01_create_table_articles.sql
- src/model/article-stores.test.ts
- src/model/couchdb/couchdb-repository.ts
- src/model/model.ts
- src/model/sqlite/sqlite-repository.ts
As we've agreed to pre-process the JSON, this is no longer needed for post-processing.
> Remove document from stored article

- src/model/couchdb/couchdb-repository.ts
We called object spread before storing the document in CouchDB. This
copied all the source fields rather than just those defined in the
target type, including the entire HTML document. We then separately
stored the HTML as an attachment.
> Fix CouchDB repo storing too many fields

- jest.config.ts
- package.json
- src/article/article-flags.test.ts
- src/article/header.test.ts
- src/article/jump-menu.test.ts
- src/data-loader/conversion/encode.test.ts
- test-utils/jats-examples/example.xml
- yarn.lock
This evening, I noticed the HTML content has disappeared from the articles on EPP.
At first I thought it was something me or @will-byrne did (we did quite a bit of removing unused data from the databases), but it turns out to be a renovate-upgraded package from stencila.
It would be worth investigating the failure ~(and if we should add a test to pick it up)~ [added in a later commit], but to get the live system up and running, I've downgraded the package and tested that it restored functionality.
> Fix issue with HTML output by downgrading stencila schema

- src/utils/logger.ts
This could do with being configured, but config.ts depends on logger.
> increase logging level to debug. 

- docker-compose.yaml
add the mongo gui to docker-compose. It runs on port 8081 for now but we can change that if need be.
> add mongo express

- docker-compose.yaml
Straightforward issue: the server runs currently, but it's embedding images again because of missing env var config for iiif server, probably lost when we removed all other backends.
> fix: docker-compose is missing config for iiif server

- src/server.ts
Refined endpoints:
- moved to `/api/reviewed-preprints` base path:
- `/` returns article summaries preprint as described in the server types
- `/{doi}/` returns an article detail, as defined by the server
- `/{doi}/metadata` returns an article detail, as defined by the client
- `/{doi}/content` returns an article content
- `/{doi}/reviews` returns an peerreview type, as defined by server
Also added some error handling, as it was such as pain trying to get client changes done when the server kept falling over due to incorrect request formats.
> Refine and add new API endpoints, add error handling

- docker-compose.yaml
- better layout of yaml into services, app and commands.
- better naming of services (dropping mongodb from app server)
- service dependency and health checks so that services don't fail if other don't start faster (mongo-express)
> improve docker-compose dev experience

- src/reviews/fetch-reviews.ts
Sciety show them in date order, but seemingly they get posted "backwards" according to their title/review number.
fixes #414
> Reverse reviews that come back from Sciety

- Dockerfile
so that docker caches the dependency steps, and only rebuilds the src layer when developing locally.
> move copying src files as the last build step, 

- Dockerfile
- package.json
- yarn.lock
Switching back to node 16.18.10 until we resolve the issues with `docker compose up` failing locally.
This is the error we are seeing. We should as a follow up introduce a test which would have prevented the renovate PR from passing it would trigger this error:
```
$ docker compose up --build
[+] Building 1.2s (3/3) FINISHED                                                                                                                                                                                           
=> [internal] load .dockerignore                                                                                                                                                                                     0.0s
=> => transferring context: 102B …
```
> Revert to node 16.18.10

- .github/workflows/ci.yaml
- .github/workflows/preview-build.yaml
change the server image tag to match the naming scheme of other EPP images.
Publishing to both tags will allow us to migrate the name in other projects a bit at a time.
> Give epp-server container images better repository name

- Dockerfile
- docker-compose.yaml
- integration-tests/api.test.ts
- src/controller/preprints-controller.ts
- src/model/model.ts
- src/model/mongodb/mongodb-repository.test.ts
- src/model/mongodb/mongodb-repository.ts
This commit updates the Dockerfile to include a setup for development environment. It also modifies the `getArticleVersion` function in `preprints-controller.ts`, `model.ts`, `mongodb-repository.ts`, and `mongodb-repository.test.ts` to handle cases where no matching article version is found. Instead of throwing an error, it now returns null, and handles the null case appropriately.
> feat: handle missing article version, update Dockerfile for dev setup

- integration-tests/mock-data/mock-body-1.json
- src/http-schema/http-schema.test.ts
- src/http-schema/http-schema.ts
- src/model/content.ts
This commit introduces changes to integration tests' mock data by adding a 'Claim' and a 'QuoteBlock'. Corresponding test cases are added in http-schema.test.ts. The http-schema.ts is updated to modify the claimType in ClaimContentSchema to be optional and add a new content field. Also, the 'QuoteBlock' option is added to the OtherContent object.
> feat: Update mock data and schema for Claim and QuoteBlock

- src/model/mongodb/mongodb-repository.ts
This is a temporary hack to match the current production behavior. Additional information can be found in the linked issues and source code lines.
> feat(mongodb-repository): reverse order of peer reviews for article version

- integration-tests/api.test.ts
- src/controller/preprints-controller.ts
- src/model/model.ts
- src/model/mongodb/mongodb-repository.ts
The getEnhancedArticlesNoContent method in the Preprints Controller, Model, and MongoDB Repository now supports pagination and sorting. It accepts 'order' (asc/desc), 'page', and 'per-page' parameters and provides a default value when these parameters are not provided. The MongoDB query has been updated with aggregate pipeline operators for matching, sorting, and grouping the results.
With the page and per-page defaulting to null then the server api will continue to return all results until client explicitly sets those values.
> feat: add pagination and sorting to getEnhancedArticlesNoContent

- src/model/mongodb/mongodb-repository.ts
Add secondary sorting by _id in mongodb repository to ensure consistent ordering when 'publishedDate' is the same.
> feat: add secondary sorting in mongodb repository

- integration-tests/api.test.ts
- src/model/model.ts
- src/model/mongodb/mongodb-repository.ts
This commit modifies the integration tests and MongoDB repository to include the first published date in the `EnhancedArticleNoContent` model. The date is determined by finding the minimum 'published' value for each document. Tests have been updated to verify this new functionality.
> feat: Add first published date to EnhancedArticleNoContent

- src/controller/preprints-controller.ts
- src/model/model.ts
- src/model/mongodb/mongodb-repository.ts
`optimise-no-content` branch:
```
> time curl  -s 'localhost:8080/api/preprints-no-content?per-page=100&page=1'  > /dev/null
real	0m0.648s
user	0m0.006s
sys	0m0.011s
[09:20:21] 650ms 0  ✔️
> time curl  -s 'localhost:8080/api/preprints-no-content?per-page=100&page=2'  > /dev/null
real	0m0.419s
user	0m0.006s
sys	0m0.012s
[09:20:25] 417ms 0  ✔️
> time curl  -s 'localhost:8080/api/preprints-no-content?per-page=100&page=3'  > /dev/null
real	0m0.483s
user	0m0.005s
sys	0m0.009s
[09:20:27] 492ms 0  ✔️
```
This branch:
```
> time curl  -s 'localhost:8080/api/preprints-no-content?per-page=100&page=1'  > /dev/null
real	0m0.151s
user	0m0.006s
sys	0m0.013s
[09:21:27] 140ms 0  ✔️
> time curl  -s 'localhost:8080/api/preprints-no-content?per-page=100&page=2'  > /dev/null
real	0m0.062s
user	0m0.006s
sys …
```
> Optimise double pipeline

- src/model/mongodb/mongodb-repository.ts
This commit includes changes to the MongoDBArticleRepository class. It now supports the handling of StoredExternalVersionSummary in addition to StoredEnhancedArticle. This adjustment is reflected in the type declarations, constructor parameters and find method modifications.
> [#1071]: update MongoDBArticleRepository to handle ExternalVersionSummary
